[FEATURE] Support container name or image
ShiraNai7/phpstorm-docker-proxy pull request #4
Opened 2022-07-23 16:41 UTC by mickaelperrin

2022-07-31 23:03 UTC, ShiraNai7 requested changes

2022-07-31 23:03 UTC, shira-374 commented on src/Config/ConfigLoader.php
> +        $data['image'] !== null or $data['container'] !== null
```suggestion
        $data['image'] !== null || $data['container'] !== null
```

`or` is only used for the error throwing part due to its low operator priority.

2022-07-31 23:03 UTC, shira-374 commented on src/Config/Config.php
> +        public string $container,
`$image` and `$container` should be nullable.

2022-07-31 23:03 UTC, ShiraNai7 commented on src/Config/ConfigLoader.php
> +            $data['image'] ?: '',
```suggestion
            $data['image'],
```

Shouldn't be needed when `Config` constructor accepts `null`s. Same with `$data['container']`.

2022-07-31 23:03 UTC, ShiraNai7 commented on src/Proxy.php
> +        $containerId = ($this->config->container !== null) ? $this->config->container : $this->getContainerId();
```suggestion
        $containerId = $this->config->container ?? $this->getContainerId();
```

2022-08-07 17:08 UTC, mickaelperrin commented
Thanks for taking time to comment my PR. I guess this is ok now.

2022-08-07 17:47 UTC, merged

2022-08-07 17:49 UTC, ShiraNai7 commented
Thanks